# Generated by Django 4.2.8 on 2025-07-11 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_published'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('featured', 'Главная новость'), ('ordinary', 'Обычная новость')], default='ordinary', max_length=10, verbose_name='Тип новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(max_length=300, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
