# Generated by Django 4.2.8 on 2025-07-12 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('summary', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='press_releases/', verbose_name='Изображение')),
                ('market', models.CharField(max_length=100, verbose_name='Рынок')),
                ('type', models.CharField(choices=[('announcement', 'Анонс'), ('event_results', 'Итоги мероприятий'), ('new_project', 'Новые проекты'), ('partnership', 'Партнерства')], max_length=20, verbose_name='Тип')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Популярный')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('contact_position', models.CharField(max_length=100, verbose_name='Должность')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Пресс-релиз',
                'verbose_name_plural': 'Пресс-релизы',
                'ordering': ['-date_published'],
            },
        ),
    ]
